version: "3"

services:
  notifier:
    image: webdevops/php-apache-dev:7.3
    volumes:
    - ./:/app/
    ports:
    - "8666:80"
    environment:
      SQL_DEBUG: 1
      IS_DEV: 1
      PHP_DEBUGGER: xdebug
      PHP_OPCACHE_MEMORY_CONSUMPTION: 192
      PHP_OPCACHE_MAX_ACCELERATED_FILES: 10000
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
      PHP_OPCACHE_REVALIDATE_FREQ: 0
      PHP_OPCACHE_INTERNED_STRINGS_BUFFER: 16
    stdin_open: true
    tty: true
